---

- hosts: all
  become: true
  tasks:

  - name: install updates (Ubuntu_
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install appache and php package
    apt:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
